### PR TITLE
Fix isPrototypeOf assert

### PR DESCRIPTION
**Pull request by maxclaus**

### CODE REVIEW

**Comment by novemberborn** [comment]
This package tracks https://nodejs.org/api/assert.html. The `return false` change was made intentionally: https://github.com/nodejs/node/pull/4166

Without thinking too hard about your change, it should be dealt with in Node.js first before it can land here.

**Comment by maxcnunes** [comment]
Alright, `if (Error.isPrototypeOf(expected))` was included to accommodate ES6 classes that extend Error. But that should return true instead of false. Or I am misunderstanding that code really badly 😕 
I will bubble this up to node project.

**Comment by novemberborn** [comment]
Note that even if this line is correct, there might be something else out of sync between this module and Node.js itself.

That said, with regards to AVA, we won't be adding workarounds for `core-assert`s behavior, since we need to move away from it entirely. All we can do here is bring `core-assert` in line with Node.js.

**Comment by maxcnunes** [comment]
Ok. So lets close it and I can open another issue in case the Node assert module gets updated.

**Pull request closed without merging**
